name: Build bottles

on: workflow_dispatch

jobs:
  build-macos-bottles:
    runs-on: macos-13
    env:
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - name: Update Homebrew
        run: brew update-reset
      - uses: actions/checkout@master
      - name: Build bottles
        run: |
          mkdir -p "$(dirname $(brew --repo ${{github.repository}}))"
          cp -a "${{github.workspace}}" "$(brew --repo ${{github.repository}})"
          mkdir "${{runner.temp}}/bottles"
          cd "${{runner.temp}}/bottles"
          brew test-bot --root-url=https://f001.backblazeb2.com/file/filippo-public musl-cross
      - name: Upload bottles
        uses: actions/upload-artifact@v1
        with:
          name: bottles
          path: ${{runner.temp}}/bottles
